import UserContext from "@/contexts/Usercontext";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body suppressHydrationWarning>
        <UserContext>{children}</UserContext>
      </body>
    </html>
  );
}

// next/navigation se useRouter
